[package]
name = "cbindgen-dep"
version = "0.1.0"
authors = ["Adam C. Foltzer <acfoltzer@acfoltzer.net>"]
edition = "2018"

[dependencies]
dep = { path = "dep" }

[build-dependencies]
cbindgen = { git = "https://github.com/eqrion/cbindgen", rev = "9197af70797620465bfe42232d3927b9a380fd3e" }
